/**
 * Master Upgrade Stage 4: 20 new SEO articles (Workstream A).
 *
 * Selected from the keyword research database (Stage 2, autocomplete
 * observation across NG, GB, US, CA). Every target keyword was checked
 * against the 25 published articles for cannibalization before writing.
 * Content rules: truthful guidance only, no fabricated statistics,
 * no fake experience claims, Nigeria-aware where relevant.
 *
 * Research source: google_autocomplete_observation_2026_09_20_no_volume_claim
 */
import type { StrategicSeoPostBrief, StrategicSeoPost } from './strategic-content';
import { SITE_URL } from '@/lib/site';

export const MASTER_UPGRADE_RESEARCH_SOURCE = 'google_autocomplete_observation_2026_09_20_no_volume_claim';
export const MASTER_UPGRADE_RESEARCH_TIMESTAMP = '2026-09-20T00:00:00.000+01:00';

const MASTER_UPGRADE_BRIEFS: StrategicSeoPostBrief[] = [];

/* ------------------------------------------------------------------ */
/* Cluster: Resume and CV fundamentals (Nigeria first)                 */
/* ------------------------------------------------------------------ */

MASTER_UPGRADE_BRIEFS.push(
  {
    slug: 'cv-format-nigeria',
    title: 'CV Format in Nigeria: The Structure Employers Actually Read',
    metaTitle: 'CV Format in Nigeria: A Practical Structure Guide',
    metaDescription: 'How to format a CV for Nigerian employers: the sections to include, the order that works, length, file format, and the mistakes that get CVs skipped.',
    targetKeyword: 'cv format nigeria',
    secondaryKeywords: ['nigerian cv format', 'cv layout for job application', 'cv structure nigeria'],
    semanticKeywords: ['CV sections', 'reverse chronological', 'PDF or Word', 'recruiter screening', 'contact details'],
    searchIntent: 'informational',
    topic: 'CV formatting for the Nigerian market',
    relatedFreeToolName: 'Free ATS Resume Scanner',
    relatedFreeToolPath: '/free-ats-resume-scanner',
    relatedFreeToolId: 'ats-resume-scanner',
    businessValue: 'HIGH',
    competition: 'MEDIUM_SERP_COMPETITION_QUALITATIVE',
    opportunityScore: 95,
    cluster: 'Resume and CV fundamentals',
    problem: 'You are applying for jobs in Nigeria and you keep hearing that your CV format matters, but most advice just shows a pretty template without explaining what recruiters and HR software actually need to find.',
    quickAnswer: 'A working Nigerian CV uses a simple order: contact details, a short professional summary, work experience in reverse chronological order, education, and skills. Keep it to one or two pages, save it as PDF unless the employer asks for Word, and use plain headings so both humans and screening software can find each section.',
    readerSituation: 'Use this guide when you are preparing a CV for graduate trainee programmes, banks, FMCG companies, tech startups, NGOs, or public sector roles in Nigeria, especially when the job advert does not tell you which format they expect.',
    workflow: ['Put your full name, phone number, email, and city at the top. Your address is not required, but Lagos or Abuja or Remote helps recruiters match location.', 'Write a 3 to 4 line professional summary that names your role, years of experience, and the type of job you want next.', 'List work experience newest first, with job title, employer, city, dates, and 3 to 5 bullet points naming what you did and the tools you used.', 'Add education with institution, degree, and years. Include NYSC if you are a recent graduate because many Nigerian employers ask for it.', 'Close with a short skills section: tools, languages, and certifications you can actually defend in an interview.'],
    example: 'Instead of writing Responsible for social media at a retail company, write Managed Instagram and Twitter for a Lagos retail brand, scheduled 5 posts weekly with Buffer, and reported engagement to the marketing lead monthly. The second version names the tools and the cadence, which is what a recruiter scans for.',
    checklist: ['Every job entry has dates, even if the jobs overlapped or were short.', 'Bullet points start with action verbs and name concrete tools or systems.', 'The file name is your name, for example Ada-Obi-CV.pdf, not CV-final-final.pdf.', 'The CV is one page for early careers, two pages maximum for experienced roles.', 'You can explain every single line in an interview without hesitation.'],
    mistakes: ['Using a photo, colored blocks, or a two-column design when you do not know the employer software.', 'Listing primary and secondary school when you already have a university degree.', 'Writing References available on request instead of using the space for skills.', 'Sending the same untouched CV to banking, tech, and NGO roles at once.'],
    toolCta: 'Before you send the CV anywhere, scan it to confirm the structure parses cleanly and nothing important is missing.',
    productCta: 'When you want to tailor one strong CV to many roles without retyping, keep your verified details in one place.',
    internalLinks: ['/free-ats-resume-scanner', '/blog/ats-friendly-resume-format-checklist', '/blog/resume-template-library-choose-ats-friendly-template', '/signup'],
    faq: [{ question: 'Should a Nigerian CV be in PDF or Word?', answer: 'Send PDF unless the job advert or recruiter asks for Word. PDF keeps your layout the same on every device. Some older applicant tracking systems prefer Word, so if the advert mentions uploading to a portal, keep a .docx copy ready.' }, { question: 'How long should a CV be in Nigeria?', answer: 'One page if you have under about five years of experience, two pages if you have more. Graduate trainee applications with many certifications can stretch to two pages, but never pad with irrelevant history.' }, { question: 'Do I need to include my date of birth or state of origin?', answer: 'Not unless the employer specifically asks. Space is better used for experience and skills. Some public sector or bank forms request these details in the application form itself, which is different from your CV.' }, { question: 'Is NYSC important on a CV?', answer: 'Yes for recent graduates. Many Nigerian employers screen for completion or exemption, so state it clearly with the year in your education section.' }],
  },
  {
    slug: 'how-to-write-a-cv',
    title: 'How to Write a CV From Scratch: A Section-by-Section Walkthrough',
    metaTitle: 'How to Write a CV: Section-by-Section Walkthrough',
    metaDescription: 'Write a CV from zero: what each section needs, how to phrase experience bullets, what to leave out, and how to check the finished CV before applying.',
    targetKeyword: 'how to write a cv',
    secondaryKeywords: ['writing a cv', 'cv writing guide', 'make a cv'],
    semanticKeywords: ['professional summary', 'experience bullets', 'skills section', 'education section', 'CV length'],
    searchIntent: 'informational',
    topic: 'CV writing from scratch',
    relatedFreeToolName: 'Free ATS Resume Scanner',
    relatedFreeToolPath: '/free-ats-resume-scanner',
    relatedFreeToolId: 'ats-resume-scanner',
    businessValue: 'HIGH',
    competition: 'HIGH_SERP_COMPETITION_QUALITATIVE',
    opportunityScore: 90,
    cluster: 'Resume and CV fundamentals',
    problem: 'Starting a CV from an empty page is paralyzing because every advice list assumes you already know what belongs in each section and how much detail is enough.',
    quickAnswer: 'Write your CV in this order: contact details, professional summary, experience, education, skills. Draft each section with rough notes first, upgrade the notes into bullets that name tools and outcomes second, and cut length third. A finished first CV should fit on one page.',
    readerSituation: 'Use this walkthrough if you are writing your first CV for internships, NYSC placements, graduate roles, or a return to work after a break, and you want concrete instructions instead of vague encouragement.',
    workflow: ['Collect your raw material first: every job, project, internship, volunteer role, and certification with dates. Do not filter while collecting.', 'Write a professional summary last even though it appears first: 3 lines naming who you are professionally and the role you want.', 'Turn each experience into bullets using the pattern action verb plus task plus tool plus result where a result exists.', 'Write education and skills honestly: institutions, years, tools, languages, certifications in progress marked clearly.', 'Read the whole CV aloud once. Anything you cannot explain naturally gets rewritten or removed.'],
    example: 'A customer service bullet upgrade: Handled customer complaints becomes Resolved an average queue of 40 daily customer tickets in Zendesk, escalating billing cases within company policy. The tools, volume, and judgment call are now visible.',
    checklist: ['Every bullet starts with a verb and most name a tool, system, or method.', 'Dates are complete and consistent across sections.', 'The summary matches the type of role you are applying to, not your entire life story.', 'Nothing on the CV exaggerates your involvement or claims a result you cannot source.', 'A friend can read the CV in 60 seconds and repeat back what you do.'],
    mistakes: ['Writing vague self-descriptions like team player and hard worker instead of evidence.', 'Listing duties without any tools, scale, or context.', 'Saving the CV as a low-quality scan or photo of a document.', 'Including every job you ever held instead of the ones relevant to the target role.'],
    toolCta: 'Run the finished draft through a scan to catch missing sections, vague verbs, and parseability problems before your first application.',
    productCta: 'If writing CVs for different roles feels repetitive, store your verified experience once and generate tailored documents from it.',
    internalLinks: ['/free-ats-resume-scanner', '/blog/cv-format-nigeria', '/free-resume-summary-generator', '/signup'],
    faq: [{ question: 'What is the difference between a CV and a resume?', answer: 'In most hiring contexts, including Nigeria and the UK, the words are used interchangeably for the one to two page document summarizing your experience. In US academic contexts a CV is a longer research document. See our CV vs resume guide for the full breakdown.' }, { question: 'How do I write a CV with no work experience?', answer: 'Use education, NYSC, internships, volunteer work, personal projects, and coursework. Bullets about real projects demonstrate the same skills employers test for: tools, ownership, and communication.' }, { question: 'Should I pay someone to write my CV?', answer: 'You can, but you must supply the facts either way, and interviewers ask about content you did not write. Learning the structure yourself, then using a scanner to check it, keeps the CV defensible.' }],
  },
  {
    slug: 'cv-vs-resume-difference',
    title: 'CV vs Resume: The Real Difference and Which One to Send',
    metaTitle: 'CV vs Resume: The Difference and Which to Send',
    metaDescription: 'CV or resume? The honest answer by country and industry: what each word means in Nigeria, the UK, the US, and academia, and what employers actually expect.',
    targetKeyword: 'cv vs resume',
    secondaryKeywords: ['difference between cv and resume', 'is a cv a resume', 'resume vs cv which to use'],
    semanticKeywords: ['curriculum vitae', 'length', 'region differences', 'academic CV', 'hiring documents'],
    searchIntent: 'informational',
    topic: 'CV versus resume terminology',
    relatedFreeToolName: 'Free ATS Resume Scanner',
    relatedFreeToolPath: '/free-ats-resume-scanner',
    relatedFreeToolId: 'ats-resume-scanner',
    businessValue: 'MEDIUM_HIGH',
    competition: 'MEDIUM_SERP_COMPETITION_QUALITATIVE',
    opportunityScore: 82,
    cluster: 'Resume and CV fundamentals',
    problem: 'Job adverts use CV and resume interchangeably, and advice pages contradict each other, so you cannot tell whether sending the wrong word signals that you do not understand the market.',
    quickAnswer: 'In Nigeria and the UK, CV is the standard word for the one to two page document, and resume means the same thing. In the US and Canada, resume is the standard word for that document, while CV usually refers to the long academic research record. Match the word the job advert uses and keep the document short unless you are applying for academic positions.',
    readerSituation: 'Use this guide when you are applying across markets, for example remote roles at US companies while living in Nigeria, or when an application form asks for a CV but your document is titled resume.',
    workflow: ['Check which word the job advert uses and mirror it in your file name and any cover email.', 'Keep the core document identical: contact details, summary, experience, education, skills.', 'For US and Canadian private sector roles, call it a resume and keep it to one or two pages.', 'For academic, research, or lectureship roles anywhere, prepare a longer CV with publications, grants, and teaching listed.', 'For Nigerian and UK roles, use the word CV and keep the same short structure.'],
    example: 'If a Lagos fintech advert says submit your resume and a New York startup says email your CV, both expect the same short document. Neither expects a 6-page academic record, and neither will penalize the other word.',
    checklist: ['The document title in your file name matches the market convention or simply uses your name.', 'Length fits the market: short everywhere except academic CVs.', 'You have a separate long-form academic CV only if you are pursuing research or teaching roles.', 'The content is identical regardless of the word: evidence of skills with tools and dates.', 'Spelling matches the market you are sending to: UK spelling for the UK and Nigeria, US spelling for the US.'],
    mistakes: ['Sending a 10-page academic CV to a private sector role because someone said CVs are long.', 'Renaming your file resume.pdf for a US role but leaving UK spelling errors inside.', 'Assuming resume means something structurally different and rebuilding your document from scratch.', 'Adding photos or personal details your target market does not expect, on the advice of a template built for another country.'],
    toolCta: 'Whatever word the advert uses, scan the document before sending to confirm it reads cleanly.',
    productCta: 'Keep one master record of your experience and produce correctly named documents for each market.',
    internalLinks: ['/blog/cv-format-nigeria', '/blog/how-to-write-a-cv', '/free-ats-resume-scanner', '/signup'],
    faq: [{ question: 'Which is longer, a CV or a resume?', answer: 'It depends on the region. In academic contexts a CV is longer because it lists publications and grants. In everyday hiring in Nigeria, the UK, and much of the world, a CV and a resume are the same short document.' }, { question: 'Do Nigerian employers prefer the word CV?', answer: 'Yes, CV is the common term in Nigeria. Nobody rejects an application for saying resume, but mirroring the advert language is the safest habit.' }, { question: 'Can I use the same document for UK and US applications?', answer: 'Yes, with spelling adjusted and the file renamed to match convention. The structure stays the same.' }],
  },
  {
    slug: 'graduate-cv-no-experience',
    title: 'Graduate CV With No Experience: What to Put on the Page',
    metaTitle: 'Graduate CV With No Experience: What to Write',
    metaDescription: 'No work experience yet? Build a graduate CV from NYSC, projects, coursework, and volunteering, with example bullets you can adapt honestly.',
    targetKeyword: 'graduate cv no experience',
    secondaryKeywords: ['cv for fresh graduate', 'entry level cv nigeria', 'first cv no experience'],
    semanticKeywords: ['NYSC', 'internship', 'coursework projects', 'volunteer work', 'transferable skills'],
    searchIntent: 'informational',
    topic: 'First CV for graduates',
    relatedFreeToolName: 'Free ATS Resume Scanner',
    relatedFreeToolPath: '/free-ats-resume-scanner',
    relatedFreeToolId: 'ats-resume-scanner',
    businessValue: 'HIGH',
    competition: 'MEDIUM_SERP_COMPETITION_QUALITATIVE',
    opportunityScore: 93,
    cluster: 'Resume and CV fundamentals',
    problem: 'Every CV template assumes you already have employers to list, so fresh graduates end up with a page of education and nothing that shows what they can actually do.',
    quickAnswer: 'Treat NYSC, internships, final year projects, coursework, and volunteer work as experience, because they are. Write each one like a job: role, organization, dates, and bullets naming the tools you used and what you produced. A graduate CV built this way fills a page without inventing anything.',
    readerSituation: 'Use this guide if you just finished university or NYSC, you are applying for graduate trainee programmes or internships, and you genuinely have no paid full-time role to list yet.',
    workflow: ['List every structured activity you have done: NYSC placement, SIWES or industrial training, church or community volunteering, class projects, hackathons, freelance gigs.', 'Pick the 3 or 4 closest to your target role and write them as experience entries with dates.', 'Turn each activity into bullets using the same verb plus task plus tool pattern employers expect from paid roles.', 'Put education high on the page with degree, institution, classification if strong, and relevant coursework.', 'Add a skills section from what you have actually used: Excel, Canva, Python, SPSS, WordPress, whatever is true.'],
    example: 'An NYSC placement bullet: Instead of Served as corps member at a school, write Taught Basic Science to JSS2 classes of about 40 students and recorded term results in the school spreadsheet during NYSC at Government College, Ilorin (2025). Teaching, class size, and record keeping are now visible.',
    checklist: ['Every experience entry has an organization name and dates.', 'Bullets name tools and numbers you can verify, not adjectives.', 'Education section includes degree, institution, and years.', 'The skills listed match tools you have genuinely used at least once.', 'The CV fits one page.'],
    mistakes: ['Claiming a job title you never held, like Manager, for volunteer coordination.', 'Leaving the experience section empty because unpaid work feels illegitimate.', 'Listing every course ever taken instead of the ones relevant to the target role.', 'Using a fake company email or an unprofessional personal email address.'],
    toolCta: 'Scan your draft to confirm sections are detectable and verbs are concrete before applying.',
    productCta: 'When interviews start converting, keep all your verified graduate experience in one reusable profile.',
    internalLinks: ['/blog/cv-format-nigeria', '/blog/how-to-write-a-cv', '/free-ats-resume-scanner', '/blog/entry-level-resume-guide', '/signup'],
    faq: [{ question: 'Can I put NYSC on my CV as experience?', answer: 'Yes. NYSC is a real placement with real responsibilities. Write it like any role: organization, location, dates, and bullets about what you did with which tools.' }, { question: 'Should I include my CGPA?', answer: 'Include it if it is strong or if the employer asks. If it is not, your coursework, projects, and skills sections carry the weight instead.' }, { question: 'How do I write a summary with no experience?', answer: 'Name your degree, your target role, and two or three concrete strengths backed by projects or NYSC. Keep it to three lines and skip soft adjectives.' }],
  },
  {
    slug: 'entry-level-resume-guide',
    title: 'Entry-Level Resume Guide: Getting Noticed Without Seniority',
    metaTitle: 'Entry-Level Resume Guide for First Applications',
    metaDescription: 'How to write an entry-level resume that competes: lead with education and projects, quantify what you can, and target each application properly.',
    targetKeyword: 'entry-level resume',
    secondaryKeywords: ['entry level resume examples', 'junior resume', 'first job resume'],
    semanticKeywords: ['projects section', 'coursework', 'internships', 'junior roles', 'tailoring'],
    searchIntent: 'informational',
    topic: 'Entry-level resume writing',
    relatedFreeToolName: 'Free Job Description Analyzer',
    relatedFreeToolPath: '/free-job-description-analyzer',
    relatedFreeToolId: 'job-description-analyzer',
    businessValue: 'HIGH',
    competition: 'MEDIUM_SERP_COMPETITION_QUALITATIVE',
    opportunityScore: 88,
    cluster: 'Resume and CV fundamentals',
    problem: 'Entry-level applicants compete against each other with near-identical education sections, so the resume that wins is the one showing evidence, not enthusiasm.',
    quickAnswer: 'An entry-level resume leads with education or projects when experience is thin, converts coursework and internships into evidence bullets, and is tailored to each role by mirroring the skills the job description actually names. Evidence beats seniority at every screening stage.',
    readerSituation: 'Use this guide when applying for your first paid roles, internships converting to full time, or junior positions where the advert says 0 to 2 years experience.',
    workflow: ['Analyze the job description first and list the skills it names, so your resume answers the advert instead of guessing.', 'Order sections by strength: education first if it is your strongest asset, projects first if they better prove the skills.', 'Write project bullets that state the problem, the tools, and the outcome you can demonstrate.', 'Mirror the advert skill names where truthful, using the exact words the employer used.', 'Keep the resume to one page and cut anything that does not support the specific application.'],
    example: 'A final year project bullet: Built a hostel allocation app as a final year project using HTML, CSS and JavaScript, tested with 30 classmates and presented results to the department panel. The scope, stack, and validation are all real and checkable.',
    checklist: ['The top third of the resume matches the target role type.', 'Projects and internships have dates, tools, and concrete outputs.', 'Skills named in the job advert appear in your resume where truthful.', 'One page, no filler sections like hobbies unless they add hard evidence.', 'Each application got at least a summary and skills tweak.'],
    mistakes: ['Sending one generic resume to 50 adverts and calling it volume.', 'Inflating internships into full-time roles or inflating titles.', 'Listing objectives like seeking a challenging position instead of evidence.', 'Hiding real project work because it was not paid.'],
    toolCta: 'Paste the job description into the analyzer to see exactly which requirements your resume should answer.',
    productCta: 'Let Jobiest keep your verified entry-level history so each tailored resume starts from truth.',
    internalLinks: ['/free-job-description-analyzer', '/blog/graduate-cv-no-experience', '/blog/find-resume-keywords-in-job-description', '/blog/ats-friendly-resume-format-checklist', '/signup'],
    faq: [{ question: 'Should an entry-level resume have a summary or an objective?', answer: 'A short summary naming your degree, target role, and two concrete strengths beats a generic objective. If you have literally nothing to summarize yet, a one-line target statement under your name works.' }, { question: 'How many bullets per project or internship?', answer: 'Two to four strong bullets. Each one should carry a tool, a task, or a measurable outcome rather than restating the project title.' }, { question: 'Do I need a different resume for every application?', answer: 'The base stays the same. Adjust the summary and mirror the advert skill names where truthful. Full rewrites are unnecessary; zero tailoring is the real mistake.' }],
  },
  {
    slug: 'professional-cv-examples',
    title: 'Professional CV Examples: What Strong CVs Have in Common',
    metaTitle: 'Professional CV Examples: What Good CVs Share',
    metaDescription: 'Instead of copying templates, learn the patterns strong professional CVs share: evidence bullets, clean structure, honest metrics, and market fit.',
    targetKeyword: 'professional cv examples',
    secondaryKeywords: ['good cv examples', 'cv samples', 'best cv format examples'],
    semanticKeywords: ['evidence bullets', 'structure', 'metrics', 'template patterns', 'recruiter reading'],
    searchIntent: 'informational',
    topic: 'Learning from strong CVs',
    relatedFreeToolName: 'Free ATS Resume Scanner',
    relatedFreeToolPath: '/free-ats-resume-scanner',
    relatedFreeToolId: 'ats-resume-scanner',
    businessValue: 'HIGH',
    competition: 'HIGH_SERP_COMPETITION_QUALITATIVE',
    opportunityScore: 80,
    cluster: 'Resume and CV fundamentals',
    problem: 'Example CVs online are either empty templates or fictional perfection, so copying them teaches layout without teaching what makes a CV convincing.',
    quickAnswer: 'Strong professional CVs share four things regardless of industry: a summary that names the target role, experience bullets with tools and outcomes, complete dates and section headings, and content trimmed to what the target market hires for. Copy those patterns into your own words instead of copying a template.',
    readerSituation: 'Use this guide when you have a CV draft and want to judge it the way a recruiter would, before deciding what to cut or upgrade.',
    workflow: ['Read your summary: does it name a role and level, or just describe personality.', 'Check your strongest three bullets: each should contain a verb, a tool or method, and ideally a number or scope.', 'Verify every section has a plain heading a scanner can detect: Experience, Education, Skills, Projects.', 'Compare your CV against one target job description and mark which requirements are answered and which are missing.', 'Delete one weak line for every new line you add, keeping the page count stable.'],
    example: 'A weak bullet: Worked on marketing campaigns. A strong bullet: Planned and scheduled 3 monthly email campaigns in Mailchimp for a 5,000-subscriber list and reported open rates to the growth lead. Same job, but the second shows ownership, scale, and reporting discipline.',
    checklist: ['The summary names a role, not a dream.', 'At least half your bullets contain a tool, system, or method name.', 'Numbers appear where they are real: team size, budget, volume, duration.', 'Section headings are standard words, not creative labels.', 'Nothing in the CV would embarrass you if the interviewer quoted it.'],
    mistakes: ['Copying a stylish template whose two-column layout breaks screening software.', 'Filling space with personal mission statements instead of evidence.', 'Claiming metrics you cannot source when asked how you measured them.', 'Keeping 10-year-old entries that no longer support the target role.'],
    toolCta: 'Scan your CV against the shared patterns to see which sections still look weak.',
    productCta: 'Jobiest keeps your evidence library current so strong bullets accumulate instead of getting lost.',
    internalLinks: ['/free-ats-resume-scanner', '/blog/how-to-write-a-cv', '/blog/resume-improvement-tips', '/blog/resume-template-library-choose-ats-friendly-template', '/signup'],
    faq: [{ question: 'Where can I see real CV examples for my field?', answer: 'Rather than imitation, build your own from the shared patterns in this guide and validate with a scanner. Example CVs from strangers cannot verify your facts, and interviewers probe for them.' }, { question: 'Do professional CVs need designs?', answer: 'No. Clean single-column structure with consistent spacing reads as more senior than decorative design, and it survives every screening system.' }, { question: 'How often should I update my CV?', answer: 'Refresh it whenever you complete a project worth describing, not just when job hunting. Bullets written while memory is fresh carry better detail.' }],
  },
  {
    slug: 'resume-improvement-tips',
    title: 'Resume Improvement Tips That Actually Move the Needle',
    metaTitle: 'Resume Improvement Tips That Move the Needle',
    metaDescription: 'Practical resume improvements ranked by impact: stronger bullets, honest metrics, targeted keywords, cleaner structure, and a pre-send review loop.',
    targetKeyword: 'resume improvement tips',
    secondaryKeywords: ['improve my resume', 'make resume better', 'resume upgrades'],
    semanticKeywords: ['bullet rewriting', 'metrics', 'tailoring', 'keyword match', 'review loop'],
    searchIntent: 'informational',
    topic: 'Improving an existing resume',
    relatedFreeToolName: 'Free Job Description Analyzer',
    relatedFreeToolPath: '/free-job-description-analyzer',
    relatedFreeToolId: 'job-description-analyzer',
    businessValue: 'HIGH',
    competition: 'HIGH_SERP_COMPETITION_QUALITATIVE',
    opportunityScore: 86,
    cluster: 'Resume and CV fundamentals',
    problem: 'You already have a resume, advice pages give 50 vague tips, and you cannot tell which changes actually affect your interview rate.',
    quickAnswer: 'The improvements that matter, in order: rewrite your weakest bullets with tools and outcomes, target each application against its job description, fix structural problems that block screening software, and build a review loop so every application teaches the next one. Cosmetic redesigns are last.',
    readerSituation: 'Use this guide when you are applying but not hearing back, and you suspect the resume itself is the bottleneck rather than the market.',
    workflow: ['Rank your current bullets from strongest to weakest, then rewrite the bottom half with the verb plus task plus tool plus result pattern.', 'Pick your next real job description and mark which named requirements your resume does not answer yet.', 'Add truthful language that answers those gaps where you genuinely have the experience.', 'Fix structure: standard headings, consistent dates, one column, PDF output.', 'After each application batch, note which version performed and keep the upgrade.'],
    example: 'An upgrade pass on one bullet: Handled accounts becomes Reconciled monthly vendor accounts in QuickBooks for a portfolio of 12 clients and flagged discrepancies to the finance lead. Verbs, tool, scale, and escalation behavior are now all visible.',
    checklist: ['The bottom half of your bullets are as strong as the top half.', 'Each recent application was checked against its specific job description.', 'Structure passes a scan: headings detectable, dates consistent.', 'You removed at least three weak lines in the last revision.', 'You can trace where every number on the resume came from.'],
    mistakes: ['Redesigning the layout while leaving weak content untouched.', 'Adding industry jargon you cannot define in an interview.', 'Improving the resume once and never again for six months.', 'Chasing a 100 percent keyword match score with unsupported claims.'],
    toolCta: 'Analyze the next job description before editing, so improvements target evidence the employer asked for.',
    productCta: 'Jobiest turns your verified history into role-specific documents so improvement compounds instead of restarting.',
    internalLinks: ['/free-job-description-analyzer', '/blog/find-resume-keywords-in-job-description', '/free-ats-resume-scanner', '/blog/professional-cv-examples', '/signup'],
    faq: [{ question: 'How do I know if my resume is the problem?', answer: 'If you apply to roles you genuinely fit and hear nothing across many applications, the resume or targeting is the likely bottleneck. Scan it, compare it to the job descriptions, and upgrade the weakest bullets first.' }, { question: 'Is a professional rewrite service worth it?', answer: 'A service can polish language, but it cannot invent your facts. If you understand the bullet pattern and review loop in this guide, self-improvement with scanning is usually enough.' }, { question: 'How much do keywords matter versus content?', answer: 'Keywords get you found by matching software; evidence gets you shortlisted by humans. Support every keyword you add with real experience.' }],
  },
);

/* ------------------------------------------------------------------ */
/* Cluster: Job discovery and applications (Nigeria first)            */
/* ------------------------------------------------------------------ */

MASTER_UPGRADE_BRIEFS.push(
  {
    slug: 'cv-review-checklist',
    title: 'CV Review Checklist: 10 Minutes Before You Hit Send',
    metaTitle: 'CV Review Checklist: Check Before You Send',
    metaDescription: 'A 10 minute CV review routine: structure, bullets, dates, contact details, file hygiene, and role fit, so nothing embarrassing reaches a recruiter.',
    targetKeyword: 'cv review',
    secondaryKeywords: ['check my cv', 'cv proofreading', 'review resume before sending'],
    semanticKeywords: ['quality check', 'consistency', 'file naming', 'contact details', 'role fit'],
    searchIntent: 'informational',
    topic: 'Self-reviewing a CV before submission',
    relatedFreeToolName: 'Free ATS Resume Scanner',
    relatedFreeToolPath: '/free-ats-resume-scanner',
    relatedFreeToolId: 'ats-resume-scanner',
    businessValue: 'MEDIUM_HIGH',
    competition: 'MEDIUM_SERP_COMPETITION_QUALITATIVE',
    opportunityScore: 78,
    cluster: 'Job discovery and applications',
    problem: 'Most rejections come from small, preventable CV defects: a typo in the email, inconsistent dates, a file named draft 7, or a summary aimed at a different job entirely.',
    quickAnswer: 'Before sending any CV, run a fixed review pass: contact details, dates, bullet quality, role fit, file name and format, and one slow read-aloud. Ten minutes of structured review catches the errors that silently kill applications.',
    readerSituation: 'Use this checklist every time you apply, especially when you have tailored the CV recently and may have introduced new inconsistencies.',
    workflow: ['Confirm the phone number and email at the top are current and correctly typed; a wrong digit is unrecoverable.', 'Check every date for month and year consistency, no overlaps that look like errors, no gaps you cannot explain.', 'Read only the bullet points: do at least half name a tool, method, or number.', 'Match the summary and skills to the advert language where truthful.', 'Save as PDF named Your-Name-CV.pdf and open it once on your phone to confirm it renders.'],
    example: 'A review catch: the CV says Marketing Executive at Flourish Ltd, March 2023 to present, but the summary says two years of data analysis. The reviewer notices the mismatch even if the writer stopped seeing it weeks ago. Fix: align the summary with the real record.',
    checklist: ['Phone and email correct and current.', 'All dates complete and internally consistent.', 'Every section uses a standard heading.', 'The file opens correctly on a phone and is under about 2 MB.', 'One final read-aloud found and fixed at least one thing.'],
    mistakes: ['Relying on spellcheck alone, which accepts wrong words like manger for manager.', 'Sending a version tailored for a different company.', 'Embedding the CV as an image inside a Word file so scanners read nothing.', 'Applying at 2am without the review pass because the deadline felt urgent.'],
    toolCta: 'Finish the review with a scan for structural problems your eyes gloss over.',
    productCta: 'Jobiest keeps the reviewed master version safe so each application starts from a known-good copy.',
    internalLinks: ['/free-ats-resume-scanner', '/blog/resume-improvement-tips', '/blog/job-application-checklist', '/signup'],
    faq: [{ question: 'How long should a CV review take?', answer: 'Ten focused minutes for a familiar CV, longer after heavy edits. The point is a fixed routine, not speed.' }, { question: 'Can someone else review my CV?', answer: 'A trusted friend catching typos and confusing lines is valuable. Just ensure final facts stay yours and truthful.' }, { question: 'What is the most common defect you catch in review?', answer: 'Contact details and date inconsistencies, followed by summaries aimed at a different role than the application.' }],
  },
  {
    slug: 'remote-jobs-for-nigerians',
    title: 'Remote Jobs for Nigerians: How to Find and Win Legitimate Ones',
    metaTitle: 'Remote Jobs for Nigerians: Find and Win Them',
    metaDescription: 'How Nigerians find real remote jobs: where to look, what proof of skill employers want, payment realities, and how to apply without scams wasting your time.',
    targetKeyword: 'remote jobs nigeria',
    secondaryKeywords: ['remote jobs for nigerians', 'work from anywhere jobs', 'international remote jobs for nigerians'],
    semanticKeywords: ['portfolio', 'time zones', 'payment methods', 'async work', 'scam spotting'],
    searchIntent: 'informational',
    topic: 'Finding legitimate remote work from Nigeria',
    relatedFreeToolName: 'Free Job Description Analyzer',
    relatedFreeToolPath: '/free-job-description-analyzer',
    relatedFreeToolId: 'job-description-analyzer',
    businessValue: 'HIGH',
    competition: 'HIGH_SERP_COMPETITION_QUALITATIVE',
    opportunityScore: 91,
    cluster: 'Job discovery and applications',
    problem: 'Remote job advice for Nigerians is dominated by two failure modes: lists of job boards without preparation guidance, and scams dressed as opportunities.',
    quickAnswer: 'Winning remote work from Nigeria is a proof game: build demonstrable skills, show them in a portfolio or profile, apply to roles whose requirements you genuinely meet, and communicate time zone and collaboration habits clearly. Treat any offer that asks you to pay, promises guaranteed income, or skips interviews as a scam signal.',
    readerSituation: 'Use this guide if you are in Nigeria targeting remote roles at international companies, in customer support, writing, design, data, development, or virtual assistance, and you want a preparation-first approach.',
    workflow: ['Pick one remote-friendly skill lane and go deep enough to show completed work, not just certificates.', 'Build a simple public record: portfolio site, GitHub, or a profile with real project descriptions.', 'Apply to roles where you meet most stated requirements, and analyze each description before writing your application.', 'State your working hours overlap and communication habits plainly in applications; international teams value clarity.', 'Track applications and payment logistics together: agree the currency and payment method before accepting any offer.'],
    example: 'An application line that works: Based in Lagos (GMT+1), I overlap with European mornings and can commit to 4 hours daily overlap with US Eastern time if the role requires it. It answers the remote team question before they ask.',
    checklist: ['You can show finished work samples for your claimed skill.', 'Every application references the actual role requirements.', 'You never paid any fee to apply, train, or unlock a job.', 'Payment terms are written and agreed before you start work.', 'Your time zone and availability are stated, not discovered later.'],
    mistakes: ['Applying to everything remote with one generic CV and no portfolio.', 'Assuming remote means easy; most remote roles have stricter output accountability.', 'Accepting vague verbal offers with no written scope or payment terms.', 'Ignoring time zone fit and then struggling in silence during probation.'],
    toolCta: 'Before applying, paste the remote job description into the analyzer to separate real requirements from filler.',
    productCta: 'Jobiest organizes your remote applications so follow-ups and requirements never get lost across time zones.',
    internalLinks: ['/free-job-description-analyzer', '/blog/how-to-get-a-job-in-nigeria', '/blog/job-application-checklist', '/blog/job-application-agent-keep-context', '/signup'],
    faq: [{ question: 'Do international companies hire from Nigeria for remote roles?', answer: 'Yes, in support, engineering, design, writing, data, and virtual assistance, among others. Companies differ on country restrictions, so check the advert or ask early rather than assuming.' }, { question: 'How do I spot remote job scams?', answer: 'Three reliable signals: any request for payment, guaranteed income promises, and skipping interviews entirely. Legitimate employers verify your work before hiring, not after charging you.' }, { question: 'What skills are most remote-friendly from Nigeria?', answer: 'Skills with verifiable output: software development, design, writing, data analysis, customer support, and virtual assistance. The common thread is work you can show.' }],
  },
  {
    slug: 'online-jobs-nigeria-avoid-scams',
    title: 'Online Jobs in Nigeria: Real Options and the Scams to Avoid',
    metaTitle: 'Online Jobs in Nigeria: Real Work vs Scams',
    metaDescription: 'A clear-eyed guide to online income in Nigeria: legitimate online job types, how real online work pays, and the scam patterns that keep recycling.',
    targetKeyword: 'online jobs nigeria',
    secondaryKeywords: ['make money online nigeria', 'online work from home nigeria', 'legit online jobs'],
    semanticKeywords: ['freelancing', 'scam patterns', 'payment proof', 'skills monetization', 'due diligence'],
    searchIntent: 'informational',
    topic: 'Online work realities in Nigeria',
    relatedFreeToolName: 'Free Job Description Analyzer',
    relatedFreeToolPath: '/free-job-description-analyzer',
    relatedFreeToolId: 'job-description-analyzer',
    businessValue: 'HIGH',
    competition: 'HIGH_SERP_COMPETITION_QUALITATIVE',
    opportunityScore: 87,
    cluster: 'Job discovery and applications',
    problem: 'Searches for online jobs in Nigeria mix genuine opportunities with a heavy layer of referral schemes, registration-fee traps, and fake task platforms that target desperate job seekers.',
    quickAnswer: 'Real online income in Nigeria comes from selling a skill or output: freelancing, writing, design, development, support, tutoring, or virtual assistance, paid per work or per month. Anything that asks you to pay to join, recruit others to earn, or promises fixed returns for tasks is not a job; it is a scheme to avoid.',
    readerSituation: 'Use this guide if you are exploring online income alongside or instead of traditional employment and need to filter opportunities before investing time.',
    workflow: ['Name the skill you will be paid for. If no skill or output is named, the listing is not describing a job.', 'Check how and when payment happens: real work defines deliverables and payment terms in writing.', 'Search the company or platform name plus the word scam and read what workers, not promoters, say.', 'Never pay registration, activation, training, or verification fees for a job. Employers pay workers, not the reverse.', 'Start small: take a first paid task, confirm payment actually arrives, then scale the relationship.'],
    example: 'A pattern to recognize: a WhatsApp broadcast offers data entry paying a large fixed daily amount, requires a 5,000 naira activation fee, and pays only after you recruit three friends. All three features, upfront payment, unrealistic fixed pay, and recruitment, mark it as a scheme rather than employment.',
    checklist: ['The work and deliverables are described in writing.', 'Payment method, currency, and timing are agreed before work starts.', 'No fee of any kind changed hands for access to the job.', 'Earnings scale with your output, not with recruits.', 'First payment arrived before you invested heavily.'],
    mistakes: ['Treating telegram and WhatsApp job broadcasts as verified listings.', 'Assuming a professional-looking website means a legitimate employer.', 'Sending identity documents to unverified recruiters early in a chat.', 'Confusing investment or staking platforms with online employment.'],
    toolCta: 'For any formal online role, analyze the job description to see if real requirements exist at all.',
    productCta: 'Jobiest keeps genuine applications organized so your energy goes to real opportunities.',
    internalLinks: ['/blog/remote-jobs-for-nigerians', '/free-job-description-analyzer', '/blog/how-to-get-a-job-in-nigeria', '/signup'],
    faq: [{ question: 'Are all online jobs in Nigeria scams?', answer: 'No. Skilled remote freelancing, support roles, tutoring, and virtual assistance are real and pay real money. The scams are the ones with upfront fees, recruitment requirements, or guaranteed fixed returns.' }, { question: 'What is the safest first step into online income?', answer: 'Pick one marketable skill, do two or three small real projects even for modest pay, get paid through a verifiable method, and build from confirmed payments rather than promises.' }, { question: 'Someone asked for my BVN to process my online job application. Is that normal?', answer: 'No legitimate online job needs your BVN before hiring you. Treat requests for BVN, bank details, or identity documents early in a chat as a serious warning sign.' }],
  },
  {
    slug: 'how-to-get-a-job-in-nigeria',
    title: 'How to Get a Job in Nigeria: A Straightforward Process',
    metaTitle: 'How to Get a Job in Nigeria: The Process',
    metaDescription: 'A realistic process for getting hired in Nigeria: pick a lane, prepare evidence, apply with quality over volume, and follow up without desperation.',
    targetKeyword: 'how to get a job in nigeria',
    secondaryKeywords: ['getting a job in nigeria', 'job hunting nigeria', 'naija job search tips'],
    semanticKeywords: ['job boards', 'referrals', 'follow up', 'recruiters', 'interview preparation'],
    searchIntent: 'informational',
    topic: 'End-to-end job search in Nigeria',
    relatedFreeToolName: 'Free Job Description Analyzer',
    relatedFreeToolPath: '/free-job-description-analyzer',
    relatedFreeToolId: 'job-description-analyzer',
    businessValue: 'HIGH',
    competition: 'HIGH_SERP_COMPETITION_QUALITATIVE',
    opportunityScore: 92,
    cluster: 'Job discovery and applications',
    problem: 'Job searching in Nigeria often feels like shouting into a void: hundreds of applications, few responses, and advice that boils down to keep applying without explaining what actually changes outcomes.',
    quickAnswer: 'Getting hired in Nigeria is a targeting problem before it is a volume problem: choose a specific role lane, prepare evidence for it, apply where you meet real requirements, use your network for referrals, and follow up politely. Quality applications to matching roles outperform mass spraying everywhere.',
    readerSituation: 'Use this guide if you are job hunting in Nigeria across any industry, whether fresh from NYSC or switching roles mid-career, and the scattergun approach is not working.',
    workflow: ['Define one target role and industry lane for the next 60 days; applications outside the lane dilute your story.', 'Prepare the evidence pack for that lane: tailored CV, LinkedIn profile, and two or three work samples or stories.', 'Source openings deliberately: job boards, company career pages, and your network, tracking every application in one place.', 'Apply only where you meet most stated requirements, with a CV adjusted to each advert.', 'Follow up once after about a week, keep applying elsewhere meanwhile, and log what each stage teaches you.'],
    example: 'A focused week looks like: Monday analyze 5 matching adverts and note common requirements; Tuesday tailor the CV and write 5 applications; Wednesday message 2 contacts in the target industry for referrals; Thursday prepare interview stories for the 3 most common requirements; Friday log responses and adjust next week based on which applications moved.',
    checklist: ['Every application in the last two weeks was for the same role lane.', 'Each CV version was adjusted to its advert, not sent blind.', 'At least one referral or warm contact attempt happened this month.', 'Every application and response is tracked somewhere you can query.', 'Interview stories exist for your top five skill claims.'],
    mistakes: ['Applying to 200 roles across six industries with one CV.', 'Treating LinkedIn as a spectator activity while job hunting.', 'Following up daily, which reads as pressure rather than interest.', 'Stopping all applications while waiting for one company to respond.'],
    toolCta: 'Analyze each target advert before applying so your CV answers its actual requirements.',
    productCta: 'Jobiest manages the pipeline: applications, documents, and follow-ups in one dashboard.',
    internalLinks: ['/free-job-description-analyzer', '/blog/remote-jobs-for-nigerians', '/blog/interview-preparation-tips', '/blog/why-your-job-search-is-taking-so-long', '/signup'],
    faq: [{ question: 'How long does it take to get a job in Nigeria?', answer: 'It varies with industry, season, and how targeted your search is. A focused search with tailored applications typically shows more movement within weeks than a scattered one does in months, because screening quality improves.' }, { question: 'Do referrals really matter in the Nigerian job market?', answer: 'Yes. Many roles are filled through internal referrals before or during public advertising. A short, respectful message to people in your target industry asking about the role, not begging for favors, is the standard approach.' }, { question: 'Is it bad to follow up after applying?', answer: 'One polite follow-up after about a week is professional. Daily messages or calls hurt you. Silence after one follow-up is your cue to invest energy elsewhere.' }],
  },
  {
    slug: 'job-search-tools-guide',
    title: 'Job Search Tools: What Each One Is Actually For',
    metaTitle: 'Job Search Tools: What Each Is Actually For',
    metaDescription: 'Job search tools explained honestly: job boards, resume scanners, keyword tools, application trackers, and AI assistants, and where each fits your search.',
    targetKeyword: 'job search tools',
    secondaryKeywords: ['job hunting tools', 'best tools for job search', 'job application tools'],
    semanticKeywords: ['job boards', 'trackers', 'scanners', 'analyzers', 'AI assistance'],
    searchIntent: 'informational',
    topic: 'Using tools in a job search',
    relatedFreeToolName: 'Free Skills Matcher',
    relatedFreeToolPath: '/free-skills-matcher',
    relatedFreeToolId: 'skills-matcher',
    businessValue: 'MEDIUM_HIGH',
    competition: 'MEDIUM_SERP_COMPETITION_QUALITATIVE',
    opportunityScore: 76,
    cluster: 'Job discovery and applications',
    problem: 'Job seekers collect apps the way gyms collect resolutions: boards, trackers, scanners, AI writers, and still no system connecting them to actual interviews.',
    quickAnswer: 'Four tool types cover a job search: discovery tools that surface openings, analysis tools that decode job descriptions, document tools that check and tailor your CV, and tracking tools that keep the pipeline visible. Use one of each; more tools without a process just produce guilt.',
    readerSituation: 'Use this guide when you are setting up your job search stack and want to know which tool does what job, and which you can skip.',
    workflow: ['Pick one or two job discovery sources for your lane, including the career pages of companies you actually want.', 'Decode every serious advert with a job description analyzer before writing anything.', 'Check every tailored CV with a scanner for structure and keyword alignment.', 'Track all applications in one place: role, date, version sent, response, next action.', 'Review the pipeline weekly and drop channels that produce no interviews after a fair trial.'],
    example: 'A working stack: discover roles on one board plus two target company career pages, analyze each advert, scan each tailored CV, track everything in one dashboard, and spend Friday reviewing which applications moved. Total daily tool time: under 30 minutes, leaving the rest for actual preparation.',
    checklist: ['Every application is recorded with its CV version.', 'Each advert was analyzed before you applied.', 'Each CV was scanned before it was sent.', 'You can name your top three producing sources.', 'Tool time is a minority of your search time.'],
    mistakes: ['Collecting job boards instead of applications.', 'Letting an AI write claims your history cannot support.', 'Never reviewing which channels actually produce interviews.', 'Paying for premium tools before fixing targeting basics.'],
    toolCta: 'Start with the skills matcher to see how your experience maps to target roles.',
    productCta: 'Jobiest combines the analysis, document, and tracking layers in one flow.',
    internalLinks: ['/free-skills-matcher', '/blog/how-to-get-a-job-in-nigeria', '/free-job-description-analyzer', '/free-ats-resume-scanner', '/signup'],
    faq: [{ question: 'Do I need to pay for job search tools?', answer: 'No. The core loop, discovering roles, analyzing descriptions, checking your CV, and tracking applications, can run entirely on free tools. Premium features help at scale, not at the start.' }, { question: 'Can AI tools write my applications for me?', answer: 'AI can help draft and structure, but every claim must remain yours and verifiable. Recruiters increasingly spot generic AI output, and interviews expose unsupported lines fast.' }, { question: 'What is the single most useful tool?', answer: 'A simple application tracker. Knowing what you sent, when, and what happened converts scattered effort into a system you can improve.' }],
  },
  {
    slug: 'job-application-checklist',
    title: 'Job Application Checklist: Everything to Verify Before Sending',
    metaTitle: 'Job Application Checklist Before You Send',
    metaDescription: 'A pre-send job application checklist: documents, details, answers, deadlines, and follow-up setup, so every application is complete and trackable.',
    targetKeyword: 'job application checklist',
    secondaryKeywords: ['before you apply checklist', 'job application help', 'application mistakes'],
    semanticKeywords: ['deadline', 'requirements', 'salary expectations', 'references', 'confirmation'],
    searchIntent: 'informational',
    topic: 'Submitting complete applications',
    relatedFreeToolName: 'Free Follow-Up Email Writer',
    relatedFreeToolPath: '/free-follow-up-email-writer',
    relatedFreeToolId: 'follow-up-email-writer',
    businessValue: 'MEDIUM_HIGH',
    competition: 'MEDIUM_SERP_COMPETITION_QUALITATIVE',
    opportunityScore: 74,
    cluster: 'Job discovery and applications',
    problem: 'Applications fail on completeness: the missing document, the unanswered questionnaire field, the deadline misread, and the salary field skipped because it felt awkward.',
    quickAnswer: 'Before sending any application, verify five things: every requested document is attached in the requested format, every form field is answered, your CV matches this specific advert, the deadline and method are confirmed, and the application is logged for follow-up. Complete and ordinary beats polished and incomplete.',
    readerSituation: 'Use this checklist for every application, and especially for portal applications with many fields where a single skipped answer can auto-reject you.',
    workflow: ['Re-read the advert once and list every requested item: CV format, cover letter, portfolio, certificates, references, or questionnaire.', 'Prepare or tailor each document, matching advert language where truthful.', 'Answer every form field; if a question truly does not apply, write a brief honest note rather than leaving it blank.', 'Confirm the deadline in your time zone and the exact submission channel.', 'Log the application with date, version, and a follow-up reminder about a week out.'],
    example: 'A portal application review: the advert asks for a CV, a cover note, and portfolio links. Your submission includes the tailored PDF CV, a four paragraph cover note referencing two stated requirements, and two project links that open without login. Every box is complete, so screening judges content, not gaps.',
    checklist: ['All requested documents attached in the requested format.', 'No blank required fields anywhere in the portal.', 'CV tailored to this advert, not the last one.', 'Deadline and channel confirmed and met.', 'Application logged with follow-up date set.'],
    mistakes: ['Uploading the wrong CV version because files were named draft.', 'Leaving the salary expectation field blank when it is required, instead of researching and stating a range.', 'Sending portfolio links that require login or that expire.', 'Applying minutes before deadline with no time to fix upload errors.'],
    toolCta: 'After submitting, draft a clean follow-up email for the reminder date.',
    productCta: 'Jobiest tracks every application and its documents so nothing is ever sent half-complete.',
    internalLinks: ['/free-follow-up-email-writer', '/blog/cv-review-checklist', '/blog/how-to-get-a-job-in-nigeria', '/blog/follow-up-email-after-job-application', '/signup'],
    faq: [{ question: 'Should I always include a cover letter even if optional?', answer: 'If you genuinely want the role, a short targeted cover note adds evidence and signals effort. If the advert explicitly says do not send one, follow the instruction exactly.' }, { question: 'What do I put in a required salary field when I have no idea?', answer: 'Research the role range first. Then state a range with a note that it is negotiable depending on the full package. A researched range beats a blank field or a random guess.' }, { question: 'How soon should I follow up after applying?', answer: 'About one week after the application or the stated closing date, whichever is later, with one short polite email.' }],
  },
  {
    slug: 'interview-preparation-tips',
    title: 'Interview Preparation Tips: The Preparation That Changes Outcomes',
    metaTitle: 'Interview Preparation Tips That Change Outcomes',
    metaDescription: 'Prepare for interviews properly: research the role, build STAR stories for your claims, rehearse out loud, and handle the questions everyone forgets to prepare.',
    targetKeyword: 'interview preparation tips',
    secondaryKeywords: ['how to prepare for an interview', 'job interview tips', 'interview prep guide'],
    semanticKeywords: ['STAR stories', 'company research', 'rehearsal', 'questions to ask', 'virtual interviews'],
    searchIntent: 'informational',
    topic: 'Interview preparation',
    relatedFreeToolName: 'Free Interview Question Generator',
    relatedFreeToolPath: '/free-interview-question-generator',
    relatedFreeToolId: 'interview-question-generator',
    businessValue: 'HIGH',
    competition: 'HIGH_SERP_COMPETITION_QUALITATIVE',
    opportunityScore: 85,
    cluster: 'Career development',
    problem: 'Most interview preparation is re-reading your own CV and hoping, which is why predictable questions still catch people off guard.',
    quickAnswer: 'Interviews reward preparation in three layers: know the role and company from its own materials, turn every skill claim on your CV into a STAR story you have rehearsed aloud, and prepare the logistics and your own questions. Nine out of ten questions come from these three layers.',
    readerSituation: 'Use this guide when you land an interview for a role you care about and want to prepare beyond reading common questions the night before.',
    workflow: ['Study the job description line by line and the company public materials: product, recent news, and the team you are joining.', 'List every skill and claim on your CV, and write one STAR story, situation, task, action, result, for each.', 'Rehearse the top five stories out loud until each fits in about two minutes without notes.', 'Prepare answers for the standards: tell me about yourself, why this role, salary expectations, and a failure you learned from.', 'Prepare two or three genuine questions about the role, team, and success measures for the end of the interview.'],
    example: 'A claim converted to a story: the CV says Managed vendor payments in QuickBooks. The STAR version: at my last role, month end vendor reconciliation ran two days late, I reorganized the invoice approval steps in QuickBooks and by the second month we closed on schedule, and the finance lead kept the new process. Situation, action, result, all true.',
    checklist: ['You can explain what the company sells and to whom, in one sentence.', 'Every CV skill claim has a rehearsed story behind it.', 'Your two minute tell me about yourself answer is actually two minutes.', 'Salary expectation has a researched range, not a mood.', 'You have two or three questions ready that you actually want answered.'],
    mistakes: ['Memorizing scripted answers word for word, which collapse under one follow-up question.', 'Researching the company so shallowly that a single product question exposes it.', 'Badmouthing a previous employer when explaining why you left.', 'Having zero questions at the end, which reads as low interest.'],
    toolCta: 'Generate the likely interview questions for your exact job description and rehearse answers for each.',
    productCta: 'Jobiest keeps your verified experience organized so interview stories stay sharp and consistent.',
    internalLinks: ['/free-interview-question-generator', '/blog/star-interview-answers-job-description', '/blog/interview-question-generator-job-description', '/blog/how-to-get-a-job-in-nigeria', '/signup'],
    faq: [{ question: 'How much interview preparation is enough?', answer: 'A solid benchmark is being able to answer why this company, why this role, and one story per CV claim without notes. If any of those wobble, prepare more.' }, { question: 'How do I prepare for a virtual interview?', answer: 'Test camera, microphone, and internet on the actual platform in advance, choose a quiet plain background, and keep notes as bullet keywords rather than scripts.' }, { question: 'What if I do not know an answer during the interview?', answer: 'Say so honestly, then talk through how you would find out. Interviewers test reasoning under uncertainty as much as knowledge.' }],
  },
);

/* ------------------------------------------------------------------ */
/* Cluster: Career development and progression                        */
/* ------------------------------------------------------------------ */

MASTER_UPGRADE_BRIEFS.push(
  {
    slug: 'career-planning-guide',
    title: 'Career Planning Guide: Choosing a Direction That Fits',
    metaTitle: 'Career Planning Guide: Choose Your Direction',
    metaDescription: 'A practical career planning method: assess what you are good at, test directions cheaply, plan in two year horizons, and review honestly each year.',
    targetKeyword: 'career planning guide',
    secondaryKeywords: ['how to plan your career', 'career development plan', 'career goals'],
    semanticKeywords: ['skills audit', 'market demand', 'short experiments', 'two year horizon', 'annual review'],
    searchIntent: 'informational',
    topic: 'Structured career planning',
    relatedFreeToolName: 'Free Career Path Explorer',
    relatedFreeToolPath: '/free-career-path-explorer',
    relatedFreeToolId: 'career-path-explorer',
    businessValue: 'MEDIUM_HIGH',
    competition: 'MEDIUM_SERP_COMPETITION_QUALITATIVE',
    opportunityScore: 75,
    cluster: 'Career development',
    problem: 'Career advice swings between follow your passion and learn to code, neither of which is a plan, so most careers drift by accident and get reviewed only during crisis.',
    quickAnswer: 'Career planning is a loop, not a one-time decision: audit your real skills and interests, research which directions value them, run cheap tests like projects and conversations before committing, set a two year direction, and review each year. Plans built this way survive contact with reality.',
    readerSituation: 'Use this guide if you are early in your career, at a natural crossroads like post-NYSC, or several years into a job you chose by default rather than decision.',
    workflow: ['Audit honestly: list the skills people actually pay you or compliment you for, and the tasks that drain you.', 'Research two or three directions that use those skills, including entry requirements and typical progression.', 'Run cheap tests: a side project, a course module, or three conversations with people already doing the direction.', 'Pick one primary direction for the next two years and define what progress looks like in skills and roles.', 'Put a yearly review in your calendar: what changed in you, what changed in the market, what needs adjusting.'],
    example: 'A cheap test in action: before committing to data analysis as a direction, complete one public dataset project and talk to two working analysts about their actual week. If the work still appeals after the unglamorous parts, the direction is validated. If not, you spent two weekends, not two years.',
    checklist: ['Your current direction was chosen deliberately within the last two years.', 'You have talked to at least two people doing the target role.', 'The plan names specific skills to build, not just a job title to want.', 'Progress markers exist for the next 12 months.', 'A review date is actually scheduled.'],
    mistakes: ['Waiting for certainty before any movement; tests create clarity, deliberation alone does not.', 'Copying someone successful whose starting point and strengths were different.', 'Planning ten years out in detail when industries shift faster than that.', 'Treating one bad manager or one bad year as a signal to restart the whole plan.'],
    toolCta: 'Use the career path explorer to see where your current skills could take you.',
    productCta: 'Jobiest keeps your skills profile current so planning and applications use the same truth.',
    internalLinks: ['/free-career-path-explorer', '/blog/career-change-advice', '/blog/free-career-assessment', '/blog/skills-gap-analysis-job-description', '/signup'],
    faq: [{ question: 'How far ahead should I plan my career?', answer: 'Two years in direction, one year in concrete steps. Beyond that, plan the review, not the details, because markets and your own interests will shift.' }, { question: 'Is it too late to plan a career change at 35 or 45?', answer: 'No. You are planning with more information than you had at 22: a work history, known strengths, and known dislikes. The same loop applies, with your existing skills as the starting asset.' }, { question: 'Should I follow passion or market demand?', answer: 'The intersection. Passion without demand is a hobby; demand without any interest collapses within a few years. The loop in this guide is designed to find the overlap.' }],
  },
  {
    slug: 'career-change-advice',
    title: 'Career Change Advice: Moving Fields Without Starting From Zero',
    metaTitle: 'Career Change Advice: Switch Without Restarting',
    metaDescription: 'How to change careers without starting over: map transferable skills, bridge the gap with proof, reposition your CV, and land the first role in the new field.',
    targetKeyword: 'career change advice',
    secondaryKeywords: ['changing careers', 'switch careers', 'career transition tips'],
    semanticKeywords: ['transferable skills', 'bridge projects', 'repositioning', 'hybrid roles', 'transition plan'],
    searchIntent: 'informational',
    topic: 'Career transitions',
    relatedFreeToolName: 'Free Skills Matcher',
    relatedFreeToolPath: '/free-skills-matcher',
    relatedFreeToolId: 'skills-matcher',
    businessValue: 'MEDIUM_HIGH',
    competition: 'MEDIUM_SERP_COMPETITION_QUALITATIVE',
    opportunityScore: 79,
    cluster: 'Career development',
    problem: 'Career changers are told to be brave and start over, which is both terrifying and wrong: most successful changes transfer existing strengths rather than discarding them.',
    quickAnswer: 'Change careers by bridging, not restarting: identify the skills your target field already values in your history, build proof for the gaps with projects or certifications, reposition your CV around the intersection, and target hybrid or adjacent roles first. Each step should use your track record, not erase it.',
    readerSituation: 'Use this guide if you are moving between industries or functions, for example from banking to tech, teaching to customer success, or law to compliance tech, and you do not want to rebuild from entry level.',
    workflow: ['Map your current skills honestly, especially the portable ones: analysis, communication, stakeholder management, systems thinking.', 'Study 10 job descriptions in the target field and mark which requirements you already satisfy and which are real gaps.', 'Close the credibility gap with evidence: a portfolio project, a certification, freelance work, or volunteering in the new field.', 'Rewrite your CV summary and bullets to lead with the intersection of old strengths and new direction.', 'Apply first to hybrid and adjacent roles where your background is an advantage, not a liability.'],
    example: 'A teacher moving to customer success: classroom management becomes stakeholder handling, lesson planning becomes onboarding material design, and parent communication becomes customer communication. Two bridge items, a course and a support project, close the tooling gap. The CV now tells one story instead of two disconnected halves.',
    checklist: ['You can name the three transferable strengths your target field values in you.', 'At least one piece of new-field evidence exists: project, certification, or freelance work.', 'The CV reads as a bridge, not a discontinuity.', 'Your target list includes hybrid or adjacent roles, not only pure entry roles.', 'You can answer why this change without apologizing for your history.'],
    mistakes: ['Quitting to study full time before testing the new field at all.', 'Sending the old CV with a new objective line and hoping context transfers.', 'Applying only to dream roles while disqualifying yourself from realistic bridge roles.', 'Describing the change as escape from the old field rather than movement toward the new one.'],
    toolCta: 'Run your experience through the skills matcher to see which target roles already fit.',
    productCta: 'Jobiest keeps both your history and new direction in one verified profile for the transition.',
    internalLinks: ['/free-skills-matcher', '/blog/career-planning-guide', '/blog/free-career-assessment', '/blog/how-to-get-a-job-in-nigeria', '/signup'],
    faq: [{ question: 'Will I have to take a pay cut to change careers?', answer: 'Sometimes, especially with a hard skills gap. Bridge roles and adjacent moves often preserve most of your salary while you build the new track. Test the market before assuming a cut is mandatory.' }, { question: 'How long does a career change take?', answer: 'Commonly six months to two years from decision to first role in the new field, depending on the gap size and how consistently you build proof. Hybrid moves are faster than pure jumps.' }, { question: 'Do I need another degree?', answer: 'Rarely for industry moves. Certifications, portfolios, and done work answer the same question faster and cheaper. Degrees matter mainly for licensed or heavily credentialed fields.' }],
  },
  {
    slug: 'free-career-assessment',
    title: 'Free Career Assessment: How to Evaluate Yourself Honestly',
    metaTitle: 'Free Career Assessment: Evaluate Yourself',
    metaDescription: 'A free, honest career assessment method: test your skills against real demand, use free tools for structure, and avoid tests that sell you a personality label.',
    targetKeyword: 'career assessment free',
    secondaryKeywords: ['free career test', 'career aptitude assessment', 'skills assessment free'],
    semanticKeywords: ['self assessment', 'market signals', 'feedback', 'structured tools', 'career tests'],
    searchIntent: 'informational',
    topic: 'Self-directed career assessment',
    relatedFreeToolName: 'Free Career Path Explorer',
    relatedFreeToolPath: '/free-career-path-explorer',
    relatedFreeToolId: 'career-path-explorer',
    businessValue: 'MEDIUM',
    competition: 'MEDIUM_SERP_COMPETITION_QUALITATIVE',
    opportunityScore: 70,
    cluster: 'Career development',
    problem: 'Free career tests hand you a personality label and a list of careers, but they cannot know your local market, your actual skill level, or what you can tolerate daily.',
    quickAnswer: 'Assess yourself with evidence instead of labels: list what you are actually good at by results and feedback, test those skills against real job descriptions, use free structured tools for gaps, and validate with two or three people who have seen your work. Evidence-based self-assessment beats any questionnaire.',
    readerSituation: 'Use this guide if you are uncertain about direction and considering a career test, or if you took one and its suggestions felt disconnected from reality.',
    workflow: ['Write your evidence list: every skill with a result, a compliment, a payment, or a repeated request behind it.', 'Feed your skills into a career path tool to see role families that use them, as hypotheses, not verdicts.', 'Pull five real job descriptions from an interesting result and check which requirements you meet honestly.', 'Ask two people who have seen your work what they would hire you for; outside eyes catch blind spots in both directions.', 'Pick the direction with the best evidence fit and plan a cheap test from the career planning guide.'],
    example: 'An evidence entry: I keep getting asked to fix broken spreadsheets and build trackers, three colleagues now use my template, and I enjoyed rebuilding the church accounts sheet. That is a skills signal with proof, unlike a test result saying you are an introvert suited to library work.',
    checklist: ['Every claimed strength has at least one piece of real evidence.', 'Test results are treated as hypotheses to check, not destinations.', 'Real job descriptions were read before choosing a direction.', 'At least one outside perspective was gathered.', 'The chosen direction survived a cheap real-world test.'],
    mistakes: ['Treating a personality label as a career instruction.', 'Assessing only interests and never evidence of ability.', 'Self-assessing in isolation without market or peer signals.', 'Paying for assessments before using the free structured ones.'],
    toolCta: 'Start with the career path explorer to turn your skills into role hypotheses worth testing.',
    productCta: 'Keep your assessment evidence in Jobiest so applications and planning share the same base.',
    internalLinks: ['/free-career-path-explorer', '/blog/career-planning-guide', '/free-skills-matcher', '/blog/career-change-advice', '/signup'],
    faq: [{ question: 'Are free career tests accurate?', answer: 'They measure preferences reasonably well but know nothing about your local market or verified abilities. Use them for ideas, then validate with evidence like job descriptions and feedback from people who have seen your work.' }, { question: 'What is the best free career assessment?', answer: 'The evidence-based one you run yourself: results list, skills-to-roles mapping, real job description comparison, and outside feedback. It costs nothing and no questionnaire can replicate it.' }, { question: 'How often should I reassess?', answer: 'Yearly, or after any major change in role, industry, or interest. Skills drift and markets move; annual reassessment keeps direction current.' }],
  },
  {
    slug: 'professional-skills-development',
    title: 'Professional Skills Development: Getting Better on Purpose',
    metaTitle: 'Professional Skills Development That Sticks',
    metaDescription: 'Develop professional skills deliberately: pick skills with market demand, practice with real output, and prove growth with work you can show.',
    targetKeyword: 'professional skills development',
    secondaryKeywords: ['develop professional skills', 'workplace skills', 'upskilling guide'],
    semanticKeywords: ['deliberate practice', 'proof of skill', 'learning projects', 'feedback loops', 'market demand'],
    searchIntent: 'informational',
    topic: 'Deliberate skill development',
    relatedFreeToolName: 'Free Skills Matcher',
    relatedFreeToolPath: '/free-skills-matcher',
    relatedFreeToolId: 'skills-matcher',
    businessValue: 'MEDIUM',
    competition: 'MEDIUM_SERP_COMPETITION_QUALITATIVE',
    opportunityScore: 68,
    cluster: 'Career development',
    problem: 'Skill development advice is dominated by course lists, but courses produce certificates while employers look for output: things you have done with the skill under real conditions.',
    quickAnswer: 'Develop skills in a loop: choose a skill the market pays for, learn the fundamentals quickly, then produce real outputs that use the skill, collect feedback, and iterate. Three finished outputs with feedback beat ten completed courses on any CV.',
    readerSituation: 'Use this guide if you are upskilling for a promotion, a career move, or employability, and certificate collecting has not translated into results.',
    workflow: ['Choose one target skill with demonstrated demand: check job descriptions in your lane for what repeats.', 'Learn fundamentals fast from one solid source, then stop consuming and start producing.', 'Build real outputs: a project at work, a freelance task, a volunteer build, or a public project.', 'Get feedback from someone who already does the skill well, and revise the output once.', 'Show the finished work publicly or in applications, then choose the next skill the same way.'],
    example: 'Learning data dashboards: one fundamentals course, then rebuild a real monthly report from your current job as an interactive dashboard, get the finance lead to critique it, revise it, and put the before and after in your portfolio. One loop produces more evidence than five certificates.',
    checklist: ['The skill you are building appears repeatedly in target job descriptions.', 'At least one finished output exists per skill you claim.', 'Feedback from a skilled practitioner was applied at least once.', 'The output is visible somewhere: portfolio, workplace system, or project.', 'Learning consumption is matched by production time.'],
    mistakes: ['Confusing course completion with capability.', 'Learning skills with no market signal behind the choice.', 'Studying five skills in parallel and finishing outputs in none.', 'Hiding your work, so growth is invisible to employers.'],
    toolCta: 'Check which skills your target roles actually demand with the skills matcher.',
    productCta: 'Jobiest tracks your verified skills so development and applications stay connected.',
    internalLinks: ['/free-skills-matcher', '/blog/career-planning-guide', '/blog/skills-gap-analysis-job-description', '/blog/career-change-advice', '/signup'],
    faq: [{ question: 'How long does it take to develop a professional skill?', answer: 'Fundamentals in weeks, working competence in months of regular use, and strength in years. The loop of output plus feedback is what compresses the middle phase.' }, { question: 'Are certifications worth it?', answer: 'In licensed or tool-specific fields, yes. Elsewhere, certifications support but do not replace output. Employers reliably weight demonstrated work over course completion.' }, { question: 'How many skills should I develop at once?', answer: 'One at a time to the point of visible output. Parallel shallow learning produces certificates without capability.' }],
  },
  {
    slug: 'job-search-automation-guide',
    title: 'Job Search Automation: What to Automate and What to Keep Human',
    metaTitle: 'Job Search Automation: What Is Safe to Automate',
    metaDescription: 'An honest guide to job search automation: organizing, tracking, and drafting can be automated; judgments, claims, and approvals should stay with you.',
    targetKeyword: 'job search automation',
    secondaryKeywords: ['automate job applications', 'job search ai', 'job application automation'],
    semanticKeywords: ['approval control', 'tracking', 'drafting', 'human review', 'employer detection'],
    searchIntent: 'informational',
    topic: 'Automation boundaries in job search',
    relatedFreeToolName: 'Free Job Description Analyzer',
    relatedFreeToolPath: '/free-job-description-analyzer',
    relatedFreeToolId: 'job-description-analyzer',
    businessValue: 'HIGH',
    competition: 'MEDIUM_SERP_COMPETITION_QUALITATIVE',
    opportunityScore: 84,
    cluster: 'Career development',
    problem: 'Automation promises to apply to hundreds of jobs while you sleep, but employers report auto-submitted applications full of errors, mismatched claims, and sometimes the wrong company name.',
    quickAnswer: 'Automate the organizing: tracking applications, storing your verified history, analyzing job descriptions, and preparing drafts. Keep the human parts: deciding where to apply, verifying every claim, and approving every submission before it goes. Automation that removes your review does not scale your search; it scales your mistakes.',
    readerSituation: 'Use this guide if you are considering automation tools for volume applications, or already use one and suspect quality is suffering.',
    workflow: ['Automate the pipeline record: every application, version, date, and response in one place.', 'Automate analysis: decode each job description into requirements and keywords before you write anything.', 'Automate drafting from your verified facts: a tailored CV or cover letter draft is a starting point, never a final submission.', 'Keep human decisions: role fit, salary expectations, and company choice.', 'Approve every document before submission; read it as the person who will be interviewed on its contents.'],
    example: 'A safe automation boundary: the system tracks 30 applications, analyzes each advert, and prepares a tailored draft CV and cover note for each. You review the drafts in minutes each, correct two claims that drifted, approve 25 of them, and reject 5 roles you decided do not fit. Volume increased; judgment stayed yours.',
    checklist: ['Every submitted document was read by you immediately before sending.', 'No claim exists in any application that you cannot defend in an interview.', 'Tracking is automated enough that nothing is lost.', 'Company names and role details are correct in every application.', 'You can explain any application in your pipeline if called tomorrow.'],
    mistakes: ['Letting tools auto-submit without review, producing mismatches and errors at scale.', 'Automating claims generation from your name instead of your verified history.', 'Confusing activity volume with search progress.', 'Applying to roles you would not accept, just because automation made it easy.'],
    toolCta: 'Automate the analysis layer first: turn any job description into requirements before writing.',
    productCta: 'Jobiest automates tracking, analysis, and drafts from your verified profile, and sends nothing without your approval.',
    internalLinks: ['/free-job-description-analyzer', '/blog/job-application-agent-keep-context', '/blog/how-to-get-a-job-in-nigeria', '/blog/job-application-checklist', '/signup'],
    faq: [{ question: 'Can I automate applying to jobs completely?', answer: 'You can, but you should not. Auto-submission without review produces errors, wrong-company text, and unsupported claims, which employers notice. Automate everything up to submission and keep the approval human.' }, { question: 'Do employers detect automated applications?', answer: 'They detect the symptoms: generic text, mismatched requirements, wrong names. Reviewed, tailored applications built with automation assistance do not carry those symptoms.' }, { question: 'What is the first thing I should automate?', answer: 'Tracking, then job description analysis. Both remove real work without touching judgment, and both immediately improve application quality.' }],
  },
  {
    slug: 'salary-negotiation-preparation',
    title: 'Salary Negotiation Preparation: Know Your Number Before They Ask',
    metaTitle: 'Salary Negotiation: Prepare Before They Ask',
    metaDescription: 'Prepare for salary negotiation with evidence: research real ranges, know your walk-away, rehearse, and negotiate the whole offer, not just the number.',
    targetKeyword: 'salary negotiation tips',
    secondaryKeywords: ['negotiate salary offer', 'how to negotiate salary', 'salary discussion preparation'],
    semanticKeywords: ['market research', 'walk away point', 'total package', 'rehearsal', 'offer evaluation'],
    searchIntent: 'informational',
    topic: 'Preparing salary negotiations',
    relatedFreeToolName: 'Free Salary Insights',
    relatedFreeToolPath: '/free-salary-insights',
    relatedFreeToolId: 'salary-insights',
    businessValue: 'MEDIUM_HIGH',
    competition: 'MEDIUM_SERP_COMPETITION_QUALITATIVE',
    opportunityScore: 77,
    cluster: 'Career development',
    problem: 'Salary negotiation advice jumps to magic phrases, but negotiations are won in preparation: knowing the range, your value, and your limits before anyone speaks.',
    quickAnswer: 'Prepare salary negotiation with numbers and a plan: research the real range for the role and market, define your target and walk-away figures, list your evidence of value, rehearse the conversation once out loud, and evaluate the whole package, not only the monthly figure. Confidence in negotiation comes from preparation, not personality.',
    readerSituation: 'Use this guide when you expect an offer or are asked about salary expectations in an interview, especially in markets where salary ranges are rarely published.',
    workflow: ['Research the role range from real listings that state figures, and record what the market actually pays.', 'Set three numbers privately: your target, a realistic acceptable figure, and your walk-away.', 'Write your evidence: skills, results, and experience the role needs, in two or three lines you can say naturally.', 'Rehearse the conversation once: state expectation with range, pause, and let them respond.', 'Evaluate the complete offer: base, benefits, growth, and conditions, before responding to any part.'],
    example: 'A prepared response to what are your salary expectations: Based on the market for this role in Lagos and my four years in similar work, I am looking at a range of X to Y, and I am flexible on structure depending on the full package. One sentence, evidence anchored, and it hands the turn back.',
    checklist: ['You know what real listings state for this role and market.', 'Your target and walk-away numbers are written down privately.', 'Your value evidence is rehearsed and factual.', 'You rehearsed stating a range and then staying quiet.', 'You are evaluating the total package, not the headline figure alone.'],
    mistakes: ['Naming a single number first with no range or research behind it.', 'Accepting on the call because silence felt awkward.', 'Negotiating before the employer has decided they want you.', 'Ignoring non-salary terms like review timing, role scope, and conditions.'],
    toolCta: 'Check what real job listings explicitly state about pay for your role before the conversation.',
    productCta: 'Keep your verified experience and salary research together in Jobiest for the negotiation.',
    internalLinks: ['/free-salary-insights', '/blog/salary-insights-from-job-listings', '/blog/interview-preparation-tips', '/blog/how-to-get-a-job-in-nigeria', '/signup'],
    faq: [{ question: 'Should I state a number first or wait?', answer: 'If asked directly, give a researched range with flexibility signaled. Waiting is fine when the market has published ranges, but stalling a direct question reads as unprepared.' }, { question: 'Is negotiation risky in a weak market?', answer: 'Reasonable, evidence-based negotiation rarely loses an offer; it can clarify terms. The risk is not in asking professionally, it is in demanding without justification or ignoring stated budget constraints.' }, { question: 'How do I negotiate without a current salary benchmark?', answer: 'Anchor to market listings and your value evidence instead of your previous pay, especially when switching industries or moving from formal to remote work.' }],
  },
);

/* ------------------------------------------------------------------ */
/* Markdown assembly and exports                                       */
/* ------------------------------------------------------------------ */

function bullets(items: string[]): string {
  return items.map((item) => `- ${item}`).join('\n');
}

function withArticleSource(path: string, slug: string): string {
  const sep = path.includes('?') ? '&' : '?';
  return `${path}${sep}article-source=${slug}`;
}

function faqMarkdown(post: StrategicSeoPostBrief): string {
  return post.faq.map((item) => `**${item.question}**\n\n${item.answer}`).join('\n\n');
}

const RESOURCE_NAMES: Record<string, string> = {
  '/free-ats-resume-scanner': 'Free ATS Resume Scanner',
  '/free-job-description-analyzer': 'Free Job Description Analyzer',
  '/free-cover-letter-writer': 'Free Cover Letter Writer',
  '/free-resume-summary-generator': 'Free Resume Summary Generator',
  '/free-linkedin-headline-builder': 'Free LinkedIn Headline Builder',
  '/free-interview-question-generator': 'Free Interview Question Generator',
  '/free-skills-matcher': 'Free Skills Matcher',
  '/free-follow-up-email-writer': 'Free Follow-Up Email Writer',
  '/free-career-path-explorer': 'Free Career Path Explorer',
  '/free-salary-insights': 'Free Salary Insights',
  '/generate': 'Resume Studio',
  '/signup': 'Create a free Jobiest account',
};

function linkedRelatedResources(post: StrategicSeoPostBrief): string {
  const links = post.internalLinks
    .filter((path) => path !== '/signup')
    .map((path) => {
      const name = RESOURCE_NAMES[path];
      if (name) return `- [${name}](${withArticleSource(path, post.slug)})`;
      return `- [${path.startsWith('/blog/') ? `Guide: ${path.split('/').pop()!.replace(/-/g, ' ')}` : path}](${withArticleSource(path, post.slug)})`;
    });
  return links.length ? links.join('\n') : '';
}

function buildMasterUpgradeMarkdown(post: StrategicSeoPostBrief) {
  const toolHref = withArticleSource(post.relatedFreeToolPath, post.slug);
  const signupHref = withArticleSource('/signup', post.slug);
  const related = linkedRelatedResources(post);

  return [
    `${post.problem} This guide covers ${post.targetKeyword} with a practical workflow, honest examples, and no fabricated statistics.`,
    `## Quick answer\n\n${post.quickAnswer}`,
    `## When this guide is most useful\n\n${post.readerSituation}`,
    `## Step-by-step workflow\n\n${bullets(post.workflow)}`,
    `### Example\n\n${post.example}`,
    `## Quality checklist before you move on\n\n${bullets(post.checklist)}`,
    `## Mistakes to avoid\n\n${bullets(post.mistakes)}`,
    `## Use ${post.relatedFreeToolName} next\n\n${post.toolCta} Start with [${post.relatedFreeToolName}](${toolHref}) and keep the output tied to the specific role or career problem you are solving.`,
    `## Turn this into a consistent system\n\n${post.productCta} [Create a free Jobiest account](${signupHref}) when you want to save progress, reuse verified facts, and connect this workflow to real applications.`,
    `## Frequently asked questions\n\n${faqMarkdown(post)}`,
    related ? `## Related resources\n\n${related}` : '',
  ].filter(Boolean).join('\n\n');
}

function masterUpgradePublicationDate(index: number) {
  const start = new Date('2026-09-21T09:00:00.000Z');
  start.setUTCHours(start.getUTCHours() + index * 3);
  return start.toISOString();
}

export const MASTER_UPGRADE_POSTS: StrategicSeoPost[] = MASTER_UPGRADE_BRIEFS.map((post, index) => ({
  ...post,
  publicationOrder: index + 1,
  publicationDate: masterUpgradePublicationDate(index),
  featuredImageAlt: `${post.title} by Jobiest`,
  contentMarkdown: buildMasterUpgradeMarkdown(post),
}));

export const MASTER_UPGRADE_SLUGS = MASTER_UPGRADE_POSTS.map((post) => post.slug);
export const MASTER_UPGRADE_URLS = MASTER_UPGRADE_POSTS.map((post) => `${SITE_URL}/blog/${post.slug}`);
