import crypto from 'node:crypto';
import { NextResponse } from 'next/server';
import { requireUser } from '@/lib/auth';
import { supabaseAdmin } from '@/lib/supabase';
export const runtime='nodejs';
const MAX_BYTES=5*1024*1024;
function safeName(name:string){return name.normalize('NFKD').replace(/[^a-zA-Z0-9._-]/g,'-').replace(/-+/g,'-').slice(0,120)||'resume.pdf'}
export async function GET(){const user=await requireUser();const {data,error}=await supabaseAdmin.from('documents').select('id,kind,original_name,mime_type,byte_size,created_at').eq('user_id',user.id).order('created_at',{ascending:false});if(error)return NextResponse.json({error:'DOCUMENT_LIST_FAILED'},{status:500});return NextResponse.json({documents:data});}
export async function POST(request:Request){const user=await requireUser();const form=await request.formData();const file=form.get('file');if(!(file instanceof File))return NextResponse.json({error:'FILE_REQUIRED'},{status:400});if(file.size===0||file.size>MAX_BYTES)return NextResponse.json({error:'FILE_SIZE_INVALID'},{status:400});if(file.type!=='application/pdf')return NextResponse.json({error:'PDF_REQUIRED'},{status:400});const bytes=Buffer.from(await file.arrayBuffer());if(bytes.subarray(0,5).toString('ascii')!=='%PDF-')return NextResponse.json({error:'INVALID_PDF_SIGNATURE'},{status:400});const hash=crypto.createHash('sha256').update(bytes).digest('hex');const path=`${user.id}/${crypto.randomUUID()}-${safeName(file.name)}`;const {error:uploadError}=await supabaseAdmin.storage.from('career-documents').upload(path,bytes,{contentType:'application/pdf',upsert:false});if(uploadError)return NextResponse.json({error:'UPLOAD_FAILED'},{status:500});const {data,error:insertError}=await supabaseAdmin.from('documents').insert({user_id:user.id,kind:'MASTER_CV',original_name:safeName(file.name),storage_path:path,mime_type:'application/pdf',byte_size:file.size,sha256:hash}).select('id,kind,original_name,mime_type,byte_size,created_at').single();if(insertError){await supabaseAdmin.storage.from('career-documents').remove([path]);return NextResponse.json({error:'DOCUMENT_RECORD_FAILED'},{status:500});}return NextResponse.json({document:data},{status:201});}
